# -------------------应用----------------------
application:
  mode: dev       #开发环境 dev  test  prod
  host: localhost
  name: leetroll-App
  port: 8089
  readtimeout: 1
  writertimeout: 1

# -------------------日志----------------------
#logger:
#  path: temp/logs
#  stdout: ''
#  level: trace
#  enableddb: false      #数据库日志开关
#

# -------------------数据库----------------------
database:
  driver: postgres
  username: leetroll
  password: 123654
  host: 172.16.1.147
  port: 5432
  sslMode: disable
  dbname: leetroll

# -------------------jwt-------------------------
jwt:
  # token 密钥
  accessSecret: leetroll
  refreshSecret: numberone
  # token 过期时间 单位：秒
  timeout: 3600

# -------------------redis缓存-------------------------
redis:
  address: 172.16.1.147:6379
  password: leetroll
  db: 2

# ----------------------七牛云----------------------
qiniu:
  #AccessKey
  AK: WhRnhuuljtU1hBNKbBLkkX2T-ymTLTDs_pC7PSn4
  #SecretKey
  SK: KN9UTKLC7HKt2QMy4u7l8XSvEgLBJcy9CTtUfVTI
  PubDomain: http://pub.leetroll.com
  PubBucket: pub-img01

  VideoDomain: http://private.video.leetroll.com
  VideoBucket: leetroll-private-video

